Ui server ejs
Arman199116/BTEQ_NODE pull request #1
Opened 2019-11-25 11:12 UTC by Arman199116

2019-11-29 12:51 UTC, maryantonyan requested changes
Here are my comments for now, later will through the .js codes one more time.

2019-11-29 12:51 UTC, maryantonyan commented on web/views/bteq.ejs
> +            Logon and Set Width commands
"LOGON and SET WIDTH commands"

2019-11-29 12:51 UTC, maryantonyan commented on web/views/bteq.ejs
> +            Logon: <br />
use `<label>` tag, provide styles for that, avoid using `<br/>` tags

2019-11-29 12:51 UTC, maryantonyan commented on web/views/bteq.ejs
> +            <input type="text" name="logon" placeholder=".logon host:port/user,pass"
Provide styles instead of using `<br/>`

2019-11-29 12:51 UTC, maryantonyan commented on web/public/bteq.css
> +    font-size: 20px;
I guess this property has no effect anywhere, please check.
![image](https://user-images.githubusercontent.com/15236153/69866006-4ccee300-12bc-11ea-8b21-bada5439531e.png)

2019-11-29 12:51 UTC, maryantonyan commented on web/views/bteq.ejs
> +            BTEQ is optimized for learning, testing, and training.
Please, update the footer to describe the implemented tool and BTEQ itself.

> An interface that works in place of the Teradata BTEQ interface. BTEQ is a general-purpose, command-based program that allows users to communicate with one or more Teradata servers, and to format reports for both print and screen output. BTEQ allows users to submit SQL queries to Teradata Database. BTEQ formats the results and returns them to the screen, a file, or to a printer.

2019-11-29 12:51 UTC, maryantonyan commented on web/public/bteq.css
> +.form_lable {
Minor: lable -> label

2019-11-29 12:51 UTC, maryantonyan commented on web/views/bteq.ejs
> +            Logon: <br />
Also, please add a little bottom margin to the label.

2019-11-29 12:51 UTC, maryantonyan commented on web/public/bteq.css
> +.form_lable > .submit_class {
Please, align submit button to the right (with red line):
![image](https://user-images.githubusercontent.com/15236153/69866962-f31be800-12be-11ea-9669-a747793c9d9e.png)

2019-11-29 12:51 UTC, maryantonyan commented on web/server.js
> +
remove empty line

2019-11-29 12:51 UTC, maryantonyan commented on web/server.js
> +app.use(bodyparser.urlencoded({ extended : false }));
remove spaces:
`app.use(bodyparser.urlencoded({extended : false}));`

2019-11-29 12:51 UTC, maryantonyan commented on web/server.js
> +    fs.writeFile(cmd_file, `${log}\n${wid}\n${sel}`, async function (err) {
remove the space:
`fs.writeFile(cmd_file, `${log}\n${wid}\n${sel}`, async function(err) {`

2019-11-29 12:51 UTC, maryantonyan commented on web/server.js
> +            res.render('bteq', {data} );
res.render('bteq', {data});

2019-11-29 12:51 UTC, maryantonyan commented on web/views/bteq.ejs
> +
remove empty line

2019-11-29 12:51 UTC, maryantonyan commented on web/exec_cmd.js
> +module.exports = async (cmd_file) => {
Remove the space:
`module.exports = async(cmd_file) => {`

2019-11-29 12:51 UTC, maryantonyan commented on web/server.js
> +    console.log("Example app listening at http://127.0.0.1:%s", port);
`Example app`??

2019-12-11 06:19 UTC, M7Arman commented on web/exec_cmd.js
> +        } catch(err) {
you can miss this try/catch, the parent try/catch will catch any exception of unlinkSync function

2019-12-11 06:19 UTC, M7Arman commented on web/server.js
> +const port = 3000;
Why cmd_file is defined using **var** keyword and port is defined with **const** keyword?

2019-12-11 06:19 UTC, M7Arman commented on web/server.js
> +    var logon = undefined;
can you use **let** instead of **var**? Also, please read why it's more preferable.

2019-12-11 06:19 UTC, M7Arman commented on web/server.js
> +
why did you initialize the variables with undefined?

2019-12-11 06:19 UTC, M7Arman commented on web/server.js
> +            if (err) throw err;
no need to catch this exception?

2019-12-11 06:19 UTC, M7Arman commented on web/server.js
> +                if (err) throw err;
no need to catch this exception?

2019-12-11 13:28 UTC, M7Arman commented on web/server.js
> +                    if (err) console.error(err);
in API functions you HAVE TO respond to the client. With your implementation, you didn't respond in this case.

2019-12-11 13:28 UTC, M7Arman commented on web/server.js
> +            if (err) console.error(err);
the same here. missing response handling

2019-12-13 06:37 UTC, maryantonyan approved these changes

2019-12-13 07:18 UTC, merged